## Intro to Scikit-learn

A demonstration of SKlearn process(es)


In [ ]:
0. End-to-end scikit-learn workflow
1. Getting data ready
2. Choosing the right model/estimator/algorithm
3. Fit the model/splitting the data to make predicitions out of it.
4. Evaluating the model
5. Improving the model
6. Save and load the trained model

## The scikit-learn workflow

In [2]:
## 1. Getting the data ready

import pandas as pd

heart_disease = pd.read_csv('./documents/heart_disease.csv')


In [3]:
## create x (feature matrix)

X = heart_disease.drop('target', axis=1)

## create y (label or output variable)

y = heart_disease['target']

In [4]:
## 2. Getting the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [23]:
## 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
import numpy as np
#y_label = clf.predict(np.array([2,3,4,5]))
y_preds = clf.predict(X_test)
y_preds


array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [36]:
y_test

262    0
194    0
171    0
255    0
166    0
      ..
135    1
266    0
294    0
228    0
116    1
Name: target, Length: 61, dtype: int64

In [5]:
clf.score(X_train, y_train)

NameError: name 'X_train' is not defined

In [71]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

import pandas as pd

heart_disease = pd.read_csv('./documents/heart_disease.csv')

X = heart_disease.drop('target', axis=1)

y = heart_disease['target']

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [74]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [76]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0], dtype=int64)

In [77]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_preds, y_test))

              precision    recall  f1-score   support

           0       0.39      0.53      0.45        17
           1       0.79      0.68      0.73        44

    accuracy                           0.64        61
   macro avg       0.59      0.61      0.59        61
weighted avg       0.68      0.64      0.65        61



In [78]:
print(confusion_matrix(y_preds, y_test))

[[ 9  8]
 [14 30]]


In [79]:
## improve on a model

accuracy_score(y_preds, y_test)

0.639344262295082

In [61]:

import numpy as np
np.random.seed(42)
for i in range(10, 100, 10):
    print(f'Trying model with {i} estimators..')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f'Model accurary on test set: {clf.score(X_test, y_test) * 100:.2f}%')
    print('')

Trying model with 10 estimators..
Model accurary on test set: 73.77%

Trying model with 20 estimators..
Model accurary on test set: 68.85%

Trying model with 30 estimators..
Model accurary on test set: 68.85%

Trying model with 40 estimators..
Model accurary on test set: 65.57%

Trying model with 50 estimators..
Model accurary on test set: 67.21%

Trying model with 60 estimators..
Model accurary on test set: 68.85%

Trying model with 70 estimators..
Model accurary on test set: 70.49%

Trying model with 80 estimators..
Model accurary on test set: 67.21%

Trying model with 90 estimators..
Model accurary on test set: 63.93%



In [84]:
## Save and load a model

import pickle


pickle.dump(clf, open('random_forest_model.pkl', 'wb'))

loaded_model = pickle.load(open('random_forest_model.pkl', 'rb'))

In [86]:
loaded_model.score(X_test, y_test)

0.639344262295082

## Getting your data ready

# Three main things to do:

    1. Splitting data into features & labels ('X' & 'y')
    2. Filling or dropping defect values.
    3. Converting non-numerical values to numerical ones (aka feature encoding)

In [89]:
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

In [90]:
## Split into training and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [134]:
pd.read_csv('data/car-sales-extended.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/car-sales-extended.csv'

60.6