In [6]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

a3.shape

(2, 2, 4)

In [119]:
a2[2, 0:2] ## viewing arrays

array([11, 12])

### 2d array, each array has 2 element, each dimension has 4 elements.
### I.e, 2d array, with first dimension with 2 elemnt, second dimension with 4 elements. See A3:

In [ ]:
a3 = np.array([[[10,20,4,5], [30,40,7,8]], [[6,5,50,60], [4,1,70,80]]]) 

In [12]:
azeros = np.zeros(5, dtype=int)
azeros

array([0, 0, 0, 0, 0])

In [20]:
aones = np.ones((2,3))
aones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
rand_under20 = np.random.randint(20, size=(2,10,3)) ##give me a random int, with no values above 20, design in a 2d array, 
# with frst 10 ele and second 3 elem
rand_under20

60

In [60]:
tiger_generator = np.random.default_rng() ## declaring generator
tiger_generator.integers(100, size=(2,3,5)) ## building an arra from a generator, with no integers above 100 

bajjaj_generator = np.random.default_rng() ## declaring generator
bajjaj_generator.random(3) ## randomizing the gen

array([0.32216948, 0.27040001, 0.97413926])

In [83]:
np.random.seed(seed= 43) ## seed freezes your random variable to be static
freeze = np.random.randint(5, size=(5, 4))


array([[4, 0, 1, 2],
       [0, 3, 1, 3],
       [3, 2, 0, 3],
       [2, 3, 3, 1],
       [1, 2, 3, 2]])

In [98]:
np.random.seed(seed= 20) 
fre_test = np.random.rand(5,2)
fre_test

array([[0.5881308 , 0.89771373],
       [0.89153073, 0.81583748],
       [0.03588959, 0.69175758],
       [0.37868094, 0.51851095],
       [0.65795147, 0.19385022]])

In [103]:
double_random = np.random.random((5,3))
double_random

array([[0.59228702, 0.6644892 , 0.64656729],
       [0.42563648, 0.51356833, 0.50125784],
       [0.03708381, 0.7081161 , 0.6204306 ],
       [0.77780853, 0.45940947, 0.37980555],
       [0.2918922 , 0.55722886, 0.0841636 ]])

In [106]:
np.unique(freeze)

array([0, 1, 2, 3, 4])

In [154]:
np.random.seed(seed=0)
complex_array = np.random.randint(5, size=(2,3,4,5))
complex_array[:, :, :, :3] 
## give me all in the first array, all ele in 2nd, all in 3rd, end before the third in 4 

array([[[[4, 0, 3],
         [1, 3, 2],
         [0, 4, 2],
         [1, 1, 0]],

        [[3, 0, 3],
         [3, 0, 1],
         [3, 0, 1],
         [0, 2, 4]],

        [[2, 4, 2],
         [4, 0, 4],
         [1, 2, 2],
         [1, 1, 1]]],


       [[[2, 3, 0],
         [1, 2, 4],
         [4, 4, 3],
         [4, 0, 4]],

        [[0, 1, 1],
         [0, 1, 2],
         [0, 3, 2],
         [1, 0, 2]],

        [[2, 3, 2],
         [3, 3, 3],
         [4, 1, 2],
         [2, 1, 4]]]])

### Arithmentic Numpy

In [11]:
import numpy as np
even = np.array([2,4,6])
odd = np.array([1,3,5])
addition = odd + even
multiplication = odd * even
subtraction = even - odd
division = even / odd
modulo = even % odd ## bringing up the remainder

array([1, 1, 1])

In [ ]:
## One bracket

In [50]:
big_array = np.array([[[11,22,33], [12,13,14], [21,22,22]],
                    [[23,34,35], [32,12,76], [89,67,54]]])

small_array = np.array([[[1,23,31], [21,45,32]],
                      [[23,43,34], [232,45,67]]])


                      
small_array.shape

(2, 2, 3)

In [46]:
#np.random.randint(5, size=(2,6,3,5))
np.log ##log
np.exp ## exponential

In [10]:
a2 = np.array([[1., 2., 3.3], [4., 5., 6.5]])
ones = np.ones(3)


In [65]:
np.random.seed(seed=34)
temp = np.random.randint(5, size=(2,3,3))
temp.shape

(2, 3, 3)

In [105]:
massive_list = np.random.random(1000)
np.random.seed(0)
massive_reduce = massive_list[:100]


47.27938395125176

In [113]:

%timeit np.sum(massive_reduce) # numpy sum is faster than python sum
%timeit sum(massive_reduce) # python sum

5.94 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
12.8 µs ± 1.57 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [112]:
#%timeit ## % line magic func
#%matplotlib inline
#how spreadout the group of data is from the mean = SD
#measure of the average degree to which each number is diff from d mean = variance.
#higher variance means wide range in number, lower variance narrow range in number 
#squuareroot of variance is the SD
#np.std, np.sqrt


In [118]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])


In [123]:
np.mean(high_var_array)
np.mean(low_var_array)

1600.1666666666667

In [124]:
np.var(high_var_array)##in high variance array, the variance is farther from the mean

4296133.472222221

In [122]:
np.var(low_var_array) ##in low variance array, the variance is closer to the mean

8.0

In [125]:
np.std(high_var_array) ## std shows how the difference of the whole group to the mean


2072.711623024829

## Dot Product

In [21]:
import numpy as np
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1.shape, mat2.T.shape ## mat2 has been transposed

((5, 3), (3, 5))

In [83]:
mat3 = np.dot(mat1, mat2.T)
mat3.shape

(5, 5)

In [211]:
points = np.random.randint(38, size=(5,5))
points

array([[32, 19,  8,  7, 23],
       [13, 17,  0, 11, 28],
       [36, 25, 32, 14, 22],
       [28, 20, 18,  4, 22],
       [35, 19,  7,  8, 13]])

In [278]:
teams = pd.DataFrame(points, columns=['AC Milan', 'Inter', 'Juve', 'Napoli', 'Roma'],
                     index=[2013, 2014, 2015, 2016, 2017])
                    
    
teams

AC Milan  Inter  Juve  Napoli  Roma
2013        32     19     8       7    23
2014        13     17     0      11    28
2015        36     25    32      14    22
2016        28     20    18       4    22
2017        35     19     7       8    13

In [273]:
bonus = np.array([3,4,5,6,7])
unique = pd.DataFrame(bonus.reshape(1,5), 
            columns=['AC Milan', 'Inter', 'Juve', 'Napoli', 'Roma'],
            index=['Maximun Points'])


In [279]:
teams['Bonus points'] = teams.dot(unique.T)
teams

AC Milan  Inter  Juve  Napoli  Roma  Bonus points
2013        32     19     8       7    23           415
2014        13     17     0      11    28           369
2015        36     25    32      14    22           606
2016        28     20    18       4    22           432
2017        35     19     7       8    13           355

In [281]:
unique.T

Maximun Points
AC Milan               3
Inter                  4
Juve                   5
Napoli                 6
Roma                   7

In [10]:
import numpy as np
np.random.seed(0)
daily_profit = np.random.randint(1000, size=(12,6))
daily_profit

array([[684, 559, 629, 192, 835, 763],
       [707, 359,   9, 723, 277, 754],
       [804, 599,  70, 472, 600, 396],
       [314, 705, 486, 551,  87, 174],
       [600, 849, 677, 537, 845,  72],
       [777, 916, 115, 976, 755, 709],
       [847, 431, 448, 850,  99, 984],
       [177, 755, 797, 659, 147, 910],
       [423, 288, 961, 265, 697, 639],
       [544, 543, 714, 244, 151, 675],
       [510, 459, 882, 183,  28, 802],
       [128, 128, 932,  53, 901, 550]])

In [82]:
import pandas as pd
monthly_sales = pd.DataFrame(daily_profit, 
             columns=['Poultry', 'Rabbitry', 
                      'Fishery', 'Orchard', 
                      'Livestock', 'Juice Sales'],
            index=['Jan', 'Feb', 'Mar', 'Apr', 
                   'May', 'Jun', 'Jul', 'Aug', 
                   'Sep', 'Oct', 'Nov', 'Dec'])


In [75]:

monthly_profit = pd.DataFrame(profit_by_category.reshape(1,6), columns=['Poultry', 'Rabbitry', 'Fishery',
                                      'Orchard', 'Livestock', 'Juice Sales'],
                             index=['Total Profits'])
monthly_profit.shape

(1, 6)

In [51]:
profit_by_category = np.array([100, 350, 35, 1200, 400, 900])
profit_by_category.reshape(1,6)




(1, 6)

In [83]:
b = monthly_sales.dot(monthly_profit.T)
monthly_sales['Total Profit per month'] = b
monthly_sales['Total Profit per month'].describe()

count    1.200000e+01
mean     1.574462e+06
std      4.633951e+05
min      1.009220e+06
25%      1.221385e+06
50%      1.441672e+06
75%      1.884860e+06
max      2.513625e+06
Name: Total Profit per month, dtype: float64

In [ ]:
df.sort_values(by=column, ascending=False)
np.sort(array_name, axis=)
np.argsort(array_name)
np.argmin
np.argmax




In [116]:
my_complex_array = np.array([[[40,20,80,60],
                     [1,2,3,4],
                     [34,44,54,65],
                     [23,12,46,87],
                     [78,98,76,54],
                     [90,67,55,44],
                     [343,454,21,33],
                     [33,444,78,98],
                     [123,2,45,77],
                     [10,100,1000,1]],
                    
                    [[21,12,31,13],
                     [11,22,33,44],
                     [231,213,415,145],
                     [9,8,7,6],
                     [6,7,8,9],
                     [234,33,444,56],
                     [90,80,70,60],
                     [21,11,111,1],
                     [88,88,88,88],
                     [7,4,1,5]],
                    
                    [[54,44,33,21],
                     [2345,678,1,2],
                     [3,5,7,9],
                     [4,5,6,7],
                     [26,78,93,3],
                     [5,65,78,32],
                     [101,13,41,28],
                     [2,3,4,5],
                     [8,98,78,68],
                     [9,99,29,39]]])



In [136]:
same_array_horizontal = np.sort(my_complex_array) ## sorts horizontally i.e in row form.
diff_array_vertical = np.sort(my_complex_array, axis=0) ## sorts vertically along the different arrays
same_array_vertical = np.sort(my_complex_array, axis=1) ##sorts vertically within the same array


## ARGSORT sorts along the index of each data. i.e returns the index number of each data in an array [1,0,3,2] representing [40,20,80,60]

In [133]:
#np.argsort(my_complex_array)

## ARGMAX is give me the index of the maximum value along a given axis..
## ARGMIN is the opposite
#### if axis 0, give that to me vertically along the different arrays
#### if axis 1, give that to me vertically within the same arrays

In [142]:
#np.argmax(my_complex_array, axis=1)
#np.argmin(my_complex_array, axis=0)

In [138]:
my_complex_array

array([[[  40,   20,   80,   60],
        [   1,    2,    3,    4],
        [  34,   44,   54,   65],
        [  23,   12,   46,   87],
        [  78,   98,   76,   54],
        [  90,   67,   55,   44],
        [ 343,  454,   21,   33],
        [  33,  444,   78,   98],
        [ 123,    2,   45,   77],
        [  10,  100, 1000,    1]],

       [[  21,   12,   31,   13],
        [  11,   22,   33,   44],
        [ 231,  213,  415,  145],
        [   9,    8,    7,    6],
        [   6,    7,    8,    9],
        [ 234,   33,  444,   56],
        [  90,   80,   70,   60],
        [  21,   11,  111,    1],
        [  88,   88,   88,   88],
        [   7,    4,    1,    5]],

       [[  54,   44,   33,   21],
        [2345,  678,    1,    2],
        [   3,    5,    7,    9],
        [   4,    5,    6,    7],
        [  26,   78,   93,    3],
        [   5,   65,   78,   32],
        [ 101,   13,   41,   28],
        [   2,    3,    4,    5],
        [   8,   98,   78,   68],
        [ 

In [6]:
from matplotlib.image import imread
import numpy as np

panda = imread('documents/panda.png')



panda




array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

SyntaxError: invalid syntax (Temp/ipykernel_18232/572432242.py, line 1)