In [3]:
import numpy as np
array = np.array([2,3,4,5,67,8,9,5,7]) # a vector, has single dimension
array

array([ 2,  3,  4,  5, 67,  8,  9,  5,  7])

In [7]:
array2 = np.array([[4,4,5,6], [43,7,5,4], [234,7,5,4], [5,32,1,2]]) # 4d array


In [37]:
one = np.arange(10, dtype = 'int')
one[0:10:2] ## initial:end:jump

array([0, 2, 4, 6, 8])

In [13]:
array3 = np.array([[3,4], [2,1], [67,7], [563, 1]]) ## 4d array, 2 dim or elements,
#array3[:2] ## start
array3.ndim

2

In [3]:
ls = np.linspace(0, 20, num=5) ##range start and end.. gap
ls

array([ 0.,  5., 10., 15., 20.])

ranging = numpy.array(2,20,4)

In [53]:
ranging = np.arange(2,30,3) ##start, end, jump
ranging

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [19]:
array3[0] = [9,9] ## numpy array is changeable
array3

array([[  9,   9],
       [  2,   1],
       [ 67,   7],
       [563,   1]])

In [24]:
ab = np.zeros(5, dtype = int)
ab

array([0, 0, 0, 0, 0])

In [18]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b))
d = np.delete(c, [2]) # position 2
e = np.append(d, 3) # to append
np.sort(e) ## sorting in Narray




array([1, 2, 3, 4, 5, 6])

In [9]:
abc = np.array([[5], [4], [78]])
de = np.sort(abc, axis=0) ## another form of sorting, variabl, axis(position), and order(sometimes)
fg = np.sort(abc, axis=1)
fg

array([[ 5],
       [ 4],
       [78]])

In [3]:
import numpy as np
arrayment = np.array([[[20,89,22], [19,67,54]], 
                      [[45,12,67], [19,00,34]], 
                      [[20,18,23], [19,56,98]]], dtype=int)
np.sort(arrayment, axis=1) ## axis 1 is vertical, axis 0 is horizontal

array([[[19, 67, 22],
        [20, 89, 54]],

       [[19,  0, 34],
        [45, 12, 67]],

       [[19, 18, 23],
        [20, 56, 98]]])

In [34]:
arrayment.ndim ##dimension
arrayment.shape ##shape 3d dimension, first element 2, second ele 3
arrayment.size ##size of the array
arr_reshape = arrayment.reshape(3,6)
newshape_reshape = np.reshape(arr_reshape, newshape=(2,9))
newshape_reshape

array([[20, 89, 22, 19, 67, 54, 45, 12, 67],
       [19,  0, 34, 20, 18, 23, 19, 56, 98]])

In [25]:
arrayment1 = np.array(arrayment)
arrayment1[:1] ## indexing for only the first element
arrayment1[0,1] ## first dimension but its second element
arrayment1[1,0] ## second dimension but its first element 

array([45, 12, 67])

In [63]:
ax = np.array([1,2,3,4,5,6])
ax1 = ax[:, np.newaxis] ## give me 6 dimensions with the one element
ax2 = ax[np.newaxis, :] ## give me one dimension with six element
ave = np.array([1, 2, 3, 4, 5, 6, 8])
bave = np.expand_dims(ave, axis=1) ## give me ave 8 dimension with one element since the axis is the second pos
bave1 = np.expand_dims(ave, axis=0) ## give me 1 dimension with 8 ele since the axis positio is first
bave1



array([[1, 2, 3, 4, 5, 6, 8]])

In [80]:
data = np.array([1,2,3,4,5])
data[]


array([1, 2, 3, 4, 5])

In [120]:
scale = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#print(scale[scale < 2])
sc1 = scale[scale%2!=0]
sc1



array([ 1,  3,  5,  7,  9, 11])

In [153]:
ara = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
bara = np.nonzero(ara < 5)
list_cord = list(zip(bara[0], bara[1])) ## for zipping
list_cord

for cord in list_cord:
    print(cord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [5]:
arra_stack = np.array([[45, 56], [34, 32]])
barra_stack = np.array([[23, 67], [37, 87]])

arra_vstack = np.vstack((arra_stack, barra_stack)) ##stacking vertically
arra_hstack = np.hstack((arra_stack, barra_stack)) ## stacking hori
arra_hstack

array([[45, 56, 23, 67],
       [34, 32, 37, 87]])

In [6]:
import numpy as np
x = np.arange(1, 25).reshape(2, 12)

np.hsplit(x, (2,4)) ##split such that 2,4 are not together. And every array has to be uniformly distributed. 

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [162]:
np.hsplit(x,3) ## to split array

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [171]:
ade = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = ade[0]
b1[0] = 99
b2 = ade.copy() ## var_name.copy
b2


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
dones = data+ones  ## you can add the values of array tgeda
dones.sum()

5

In [189]:
bata = np.array([[2,3], [4,6]])
bata.sum(axis=1) ##sum over axis 1
bata.sum(axis=0) #sum over axis 0
sata = bata * 4 ## assigning over different data, broadcasting
sata.min() ## minimum
sata.max() ## maximum



24

In [198]:
datu = np.array([[10,30,40,75],
               [90,45,30,70],
               [52,48,96,42]])
np.sort(datu, axis=1)

array([[10, 30, 40, 75],
       [30, 45, 70, 90],
       [42, 48, 52, 96]])

In [32]:
bansa = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]).reshape(2,10)
np.hsplit(bansa, (2,3)) ## horizontally after the 2nd and 3rd columns. 
np.vsplit(bansa, 2) ##split vertically in two equal places

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])]

In [46]:
ndata = np.array([[6, 3], [9, 6], [10, 5]])
ndata.max(axis=1) # if its zero dim or axis, 

array([ 6,  9, 10])

In [79]:
arith = np.array([[34,12], [23,21], [124,67]])
metic = np.array([1,11])
metic + arith




array([[ 35,  23],
       [ 24,  32],
       [125,  78]])

In [132]:
rng = np.random.default_rng() ## to have a generator
rng.random(5) ## .random randomly gives you a number

array([0.96550567, 0.24815665, 0.64852339, 0.39277474, 0.07682581])

In [110]:
huge_rand_int = rng.integers(100, size=(5,20,10)) ## generate me a random number not above 100, has five dimen,
                                                    ##first 20 elements and sec 10 ele
#huge_rand_int


In [117]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a) ## to slice out only the unique values
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [141]:
unique_values, indices_list = np.unique(a, return_index=True) ##returns the index num
unique_values
indices_list
#print(indices_list)
#unique_values, occur_count = np.unique(a, return_counts=True) ## returns the occurence num
#print(occur_count)

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64)

In [27]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d_uni, index_num, counts_appear = np.unique(a_2d, axis=0, return_index=True, return_counts=True)
#print(counts_appear) ## one array appears twice, and the other, once.
#print(a_2d_uni) ## gives us the unique arrays
print(index_num) ## returns the index of only the unique arrays

[0 1 2]


In [158]:
np.random.default_rng

<function numpy.random._generator.default_rng>

In [172]:
shape = np.arange(1,16)
resha = np.arange(1,16).reshape(3,5)

#shape
#reshape
resha.transpose() ## to transpose or use resha.T


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])